KTHW:: Safe functions ============== making the uninstall_services functions in all componenets safe (idempotent)

diff --git a/kthw/control-plane/cp_agent.sh.template b/kthw/control-plane/cp_agent.sh.template
--- a/kthw/control-plane/cp_agent.sh.template
+++ b/kthw/control-plane/cp_agent.sh.template
@@ -63,12 +63,13 @@ __rm_if_exist() {
     return 0
 }
 
-_delete_configurations() {
+_delete_app_directories() {
     local sc=0
     __rmdir_if_exist /etc/kubernetes || sc=1
     __rmdir_if_exist /var/lib/kubernetes || sc=1
+
+    [ $sc=0 ] && log_debug "app directories removed"
     return $sc
-    
 }
 
 _delete_service_files() {
@@ -80,22 +81,19 @@ _delete_service_files() {
     return $sc
 }
 
-_create_directories() {
+_create_app_directories() {
     mkdir -p /etc/kubernetes/config || { log_error "failed to create /etc/kubernetes/config"; return 1; }
-    mkdir -p /var/lib/kubernetes || { rm -rf /etc/kubernetes/config; log_error "failed to create \
-        /var/lib/kubernetes"; return 1; }
+    mkdir -p /var/lib/kubernetes || { log_error "failed to create /var/lib/kubernetes"; return 1; }
 
     log_debug "created directories for services"
 }
 
 # again, using set -e is not a good practice, but we're doing it with caution
-_install_configurations() {
-    _create_directories || return 1
+_install_app_files() {
     # run a subshell so that we can use -e without exiting the script
     # if one copy fails, delete all
     (
     set -e
-    trap _delete_configurations ERR
     cp ${cp_home}/ca.crt /var/lib/kubernetes
     cp ${cp_home}/ca.key /var/lib/kubernetes
     cp ${cp_home}/kube-apiserver.crt /var/lib/kubernetes
@@ -124,12 +122,8 @@ _enable_services() {
     systemctl daemon-reload || { log_error "failed to daemon-reload"; return 1; }
     
     # if one of  them fails to enable, remove the services and reload daemon
-    if ! systemctl enable kube-apiserver kube-scheduler kube-controller-manager; then
-        rm /etc/systemd/system/kube-* > /dev/null 2>&1
-        systemctl daemon-reload
-        log_error "failed to enable services"
-        return 1
-    fi
+    systemctl enable kube-apiserver kube-scheduler kube-controller-manager || { \
+        log_error "failed to enable services"; return 1; }
     
     log_debug "enabled control plane services"
 
@@ -208,21 +202,23 @@ install_services() {
     fi 
     
     echo_title "installing services"
-
-    _install_configurations 
-    if [ $? != 0 ]; then  log_error "failed installing certificates and kubeonfigs"; return 1; fi 
-    _install_service_files || { _delete_configurations; log_error "failed intsalling service files"; return 1; }
-    _enable_services || { _delete_configurations; _delete_service_files; log_error "failed to enable services"; return 1; }
+    
+    _create_app_directories || { _delete_app_directories; log_error "failed to install services"; return 1; }  
+    _install_app_files
+    if [ $? != 0 ]; then 
+        _delete_app_directories
+        log_error "failed to install services" 
+        return 1
+    fi
+    _install_service_files || { uninstall_services; log_error "failed intsalling services"; return 1; }
+    _enable_services || { uninstall_services; log_error "failed to enable services"; return 1; }
 
     log_info "installed services"
 
 }
 
+## as in etcd, this function is safe (idempotent)
 uninstall_services() {
-    if [ "$(_check_services_loaded)" = "false" ]; then
-         log_warning "services already uninstalled"
-         return 2
-    fi
     if [ "$(_check_services_active)" = "true" ]; then
          log_warning "services are active, stop them first";
          return 3
@@ -230,12 +226,11 @@ uninstall_services() {
     
     echo_title "uninstalling services"
 
-    # we don't need to disable the services, just delete and they'll automatically be disabled
     local sc=0
     { _delete_service_files && systemctl daemon-reload; } || { log_error "failed to remove services"; sc=1; }
-    _delete_configurations || { log_error "failed to delete configuarions"; sc=1; }
+    _delete_app_directories || { log_error "failed to delete app directories"; sc=1; }
     
-    log_info "uninstalled services"
+    [ $sc=0 ] && log_info "control plane services uninstalled"
     return $sc
 }
 
@@ -260,7 +255,7 @@ start_services() {
     systemctl start kube-apiserver kube-scheduler kube-controller-manager || { log_error "failed to start services"; return 1;  }
     
     if systemctl is-active kube-apiserver && systemctl is-active kube-controller-manager && \
-       systemctl is-active kube-schedueler; then
+       systemctl is-active kube-scheduler; then
         log_info "started control plane services"
     else
         log_error "at least one service is down"
diff --git a/kthw/etcd/etcd_agent.sh.template b/kthw/etcd/etcd_agent.sh.template
--- a/kthw/etcd/etcd_agent.sh.template
+++ b/kthw/etcd/etcd_agent.sh.template
@@ -65,30 +65,37 @@ __rm_if_exist() {
 }
 
 
-_create_directories() {
+_create_app_directories() {
     mkdir -p /etc/etcd /var/lib/etcd || { log_error "failed to create directories"; return 1; }
     log_debug "directories created"
 }
 
-_delete_directories() {
-    __rmdir_if_exist "/etc/etcd"
-    __rmdir_if_exist "/var/lib/etcd"
+_delete_app_directories() {
+    local sc=0
+    __rmdir_if_exist "/etc/etcd" || sc=1
+    __rmdir_if_exist "/var/lib/etcd" || sc=1
     
-    log_debug "directories removed"
+    [ $sc=0 ] && log_debug "directories removed"
+    return $sc
 }
 
-_copy_certificates() {
+_copy_app_files() {
     cp $etcd_home/ca-etcd.crt /etc/etcd || { log_error "failed to copy certificates"; return 1; }
     cp $etcd_home/etcd-server.crt /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
     cp $etcd_home/etcd-server.key /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
 }
 
-_copy_unit_file() {
+_copy_service_file() {
     cp $etcd_home/etcd.service /etc/systemd/system  || { log_error "failed to copy service file"; return 1; }
 }
 
-_delete_unit_file() {
+_delete_service_file() {
     __rm_if_exist /etc/systemd/system/etcd.service 
+}
+
+_enable_service() {
+    systemctl daemon-reload || { log_error "failed to deamon-reload"; return 1; }
+    systemctl enable etcd || { log_error "failed to enable etcd"; return 1; }
 }
 
 _test_installation() {
@@ -157,8 +164,8 @@ uninstall_etcd_binaries() {
 #
 #   install etcd service
 #
-#   this function does a great deal of things:
-#   - create required directories
+#   this function does the followings:
+#   - create required directories for etcd
 #   - copy certificates to correct locations
 #   - copy service file to correct location
 #   - load and enable the service
@@ -178,19 +185,11 @@ install_service() {
 
     echo_title "installing service"
 
-    _create_directories || { log_error "failed to install service"; return 1; } 
-    _copy_certificates || { _delete_directories; log_error "failed to install service"; return 1; } 
-    _copy_unit_file || { delete_directories; log_error "failed to install service"; return 1; }
-    
-    systemctl daemon-reload || { _delete_unit_file; _delete_directories; log_error "failed to daemon-reload"; exit 1; }
-    if ! systemctl enable etcd; then
-        _delete_unit_file 
-        _delete_directories
-        systemctl daemon-reload
-        log_error "failed to enable service"
-        return 1
-    fi
-
+    _create_app_directories || { _delete_app_directories; log_error "failed to install service"; return 1; } 
+    _copy_app_files || { _delete_app_directories; log_error "failed to install service"; return 1; } 
+    _copy_service_file || { uninstall_service; log_error "failed to install service"; return 1; }
+    _enable_service || { uninstall_service; log_error "failed to enable service"; return 1; }  
+   
     log_info "etcd service is loaded and enabled"
 }
 
@@ -200,31 +199,26 @@ install_service() {
 #
 #   the undo of the install service function
 #   will do the followings:
-#   - disable the service
 #   - remove directories
 #   - remove unit file
 #   - reload services
 #
-#   runs only if service is not active and is loaded
+#   This function is safe (idempotent)
 #
 uninstall_service() {
     if [ $(_check_service_active) = "true" ]; then
         log_warning "service is active, stop service first"
         return 3
     fi
-    if [ $(_check_service_loaded) = "false" ]; then
-        log_warning "service already uninstalled"
-        return 2
-    fi
-
-    echo_title "uninstalling service"
-    systemctl disable etcd || { log_error "failed to disable service etcd"; return 1; }
-    _delete_unit_file || { log_error "failed to remove service file"; return 1; }
     
-    systemctl daemon-reload || log_error "systemctl deamon-reload failed"
-    _delete_directories || log_warning "failed to delete directories"
-
-    log_info "etcd service is unloaded, directories removed"
+    local sc=0
+    echo_title "uninstalling service"
+    { _delete_service_file && systemctl daemon-reload; } || { log_error "failed to remove service file"; sc=1; }
+    
+    _delete_app_directories || { log_error "failed to delete directories"; sc=1; }
+    
+    [ $sc=0 ] && log_info "etcd service removed"
+    return $sc
 }
 
 
@@ -244,11 +238,7 @@ start_service() {
         log_warning "service is not loaded, load service first"
         return 3
     fi
-    if [ $(_check_binaries_installed) = "false" ]; then
-        log_warning "etcd binaries uninstalled, install first"
-        return 3
-    fi
-
+    
     echo_title "starting service"
     systemctl start etcd || { log_error "failed to start etcd service"; return 1; }
 
diff --git a/kthw/workers/workers_agent.sh.template b/kthw/workers/workers_agent.sh.template
--- a/kthw/workers/workers_agent.sh.template
+++ b/kthw/workers/workers_agent.sh.template
@@ -136,15 +136,8 @@ _install_containerd() {
     systemctl is-active containerd > /dev/null 2>&1 ||  { log_error "failed to start containerd service"; _uninstall_containerd; }
 }
 
-_create_installation_directories() {
-    sudo mkdir -p /var/lib/kubelet \
-        /var/lib/kube-proxy \
-        /var/lib/kubernetes \
-        /var/run/kubernetes \
-        /etc/cni/net.d
-}
 
-_copy_files_to_locations() {
+_install_app_files() {
     cp ${workers_home}/kubelet.crt /var/lib/kubelet || return 1
     cp ${workers_home}/kubelet.key /var/lib/kubelet || return 1
     cp ${workers_home}/kubelet.kubeconfig /var/lib/kubelet || return 1
@@ -155,35 +148,46 @@ _copy_files_to_locations() {
 
 }
 
-_install_kube_service_files() {
+_install_service_files() {
     cp ${workers_home}/kubelet.service /etc/systemd/system || return 1
     cp ${workers_home}/kube-proxy.service /etc/systemd/system || return 1
 }
 
-_delete_kube_service_files() {
-    __rm_if_exist "/etc/systemd/system/kubelet.service"
-    __rm_if_exist "/etc/systemd/system/kube-proxy.service"
+_delete_service_files() {
+    local sc=0
+    __rm_if_exist "/etc/systemd/system/kubelet.service" || sc=1
+    __rm_if_exist "/etc/systemd/system/kube-proxy.service" || sc=1
+
+    return $sc
 }
 
-_create_kube_dirs() {
+_create_app_directories() {
     mkdir -p /var/lib/kubelet || return 1
     mkdir -p /var/lib/kubernetes || return 1
     mkdir -p /var/lib/kube-proxy  || return 1
     mkdir -p /var/run/kubernetes || return 1
 }
 
-_delete_kube_dirs() {
-    __rmdir_if_exist "/var/lib/kubelet"
-    __rmdir_if_exist "/var/lib/kubernetes"
-    __rmdir_if_exist "/var/lib/kube-proxy"
-    __rmdir_if_exist "/var/run/kubernetes"
+_delete_app_directories() {
+    local sc=0
+    __rmdir_if_exist "/var/lib/kubelet" || sc=1
+    __rmdir_if_exist "/var/lib/kubernetes" || sc=1
+    __rmdir_if_exist "/var/lib/kube-proxy" || sc=1
+    __rmdir_if_exist "/var/run/kubernetes" || sc=1
+
+    [ $?=0 ] && log_debug "app directories removed"
+    return $sc
 }
 
 _enable_services() {
-    systemctl daemon-reload
-    systemctl enable kubelet || return 1
-    systemctl enable kube-proxy || return 1
+    systemctl daemon-reload || { log_error "failed to daemon-reload"; return 1; }
+    
+    # if one of  them fails to enable, remove the services and reload daemon
+    systemctl enable kubelet kube-proxy ||  { log_error "failed to enable services"; return 1; }
+    
+    log_debug "enabled kubelet services"
 }
+
 
 ########################## commands functions #################################
 
@@ -293,35 +297,29 @@ install_services() {
 
     echo_title "installing services"
      
-    _create_kube_dirs || { log_error "failed to create directories for kubelet and kube-proxy"; _delete_kube_dirs; return 1; }
-    _copy_files_to_locations || { log_error "failed to copy kubelet and kube-proxy files to locations"; \
- _delete_kube_dirs; return 1; } 
-    _install_kube_service_files || { log_error "failed to install service files"; _delete_kube_dirs; \
- _delete_kube_service_files; return 1; }
-    
-    _enable_services || { log_error "failed enabling kubelet and/or kube-proxy"; return 1; }
+    _create_app_directories || { _delete_app_directories; log_error "failed to install services"; return 1; }
+    _install_app_files || { _delete_app_directories; log_error "failed to install services"; return 1; }
+    _install_service_files || { uninstall_services; log_error "failed to install services"; return 1;  } 
+    _enable_services || { uninstall_services; log_error "failed enabling kubelet and/or kube-proxy"; return 1; }
 
     log_info "installed services"
 }
 
-uninstall_services() { 
-    if [ "$(_check_services_loaded)" = "false" ]; then
-        log_warning "services already unloaded"
-        return 2
-    fi
+## as in etcd, this function is safe (idempotent)
+uninstall_services() {
     if [ "$(_check_services_active)" = "true" ]; then
-        log_warning "services are active, stop them first"
-        return 3
+         log_warning "services are active, stop them first";
+         return 3
     fi
-        
+    
     echo_title "uninstalling services"
 
-    _delete_kube_dirs
-    _delete_kube_service_files
-
-    systemctl daemon-reload || { log_error "failed to reload daemon"; return 1; }
+    local sc=0
+    { _delete_service_files && systemctl daemon-reload; } || { log_error "failed to remove services"; sc=1; }
+    _delete_app_directories || { log_error "failed to delete app directories"; sc=1; }
     
-    log_info "uninstalled_services"
+    [ $sc=0 ] && log_info "control plane services uninstalled"
+    return $sc
 }
 
 start_services() {
