KTHW:: Refactor ========== - refactoring etcd - refactoring control-plane - refactoring workers

diff --git a/kthw/control-plane/cp_agent.sh.template b/kthw/control-plane/cp_agent.sh.template
--- a/kthw/control-plane/cp_agent.sh.template
+++ b/kthw/control-plane/cp_agent.sh.template
@@ -5,8 +5,6 @@ cmd=$1
 cp_home={{CP_HOME}}
 k8s_version={{K8S_VERSION}}
 
-
-
 ## Logging functions
 
 GREEN="\e[32;1m"
@@ -50,19 +48,34 @@ log_success() {
     echo -e "${GREEN}=== $2 $RESET"
 }
 
-#####################################################################
+###################### utility functions #############
 
-### internal functions for installing/uninstalling services
+
+__rmdir_if_exist() {
+    [ -z "$1" ] && { log_error "directory not provided"; return 1; }
+    [ -d $1 ] && { rm -rf $1  || { log_error "failed to remove directory $1"; return 1; } }
+    return 0
+}
+
+__rm_if_exist() {
+    [ -z "$1" ] && { log_error "file not provided"; return 1; }
+    [ -f $1 ] && { rm -rf $1 || { log_error "failed to remove file $1"; return 1; } }
+    return 0
+}
+
 _delete_configurations() {
-    rm -rf /etc/kubernetes /var/lib/kubernetes || { log_error "failed to delete directories"; return 1; }
+    local sc=0
+    __rmdir_if_exist /etc/kubernetes || sc=1
+    __rmdir_if_exist /var/lib/kubernetes || sc=1
+    return $sc
     
 }
 
 _delete_service_files() {
     local sc=0
-    [ -f /etc/systemd/system/kube-apiserver.service ] && { rm /etc/systemd/system/kube-apiserver.service || { log_error "failed to remove service file"; sc=1; } }
-    [ -f /etc/systemd/system/kube-scheduler.service ] && { rm /etc/systemd/system/kube-scheduler.service || { log_error "failed to remove service file"; sc=1; } }
-    [ -f /etc/systemd/system/kube-controller-manager.service ] && { rm /etc/systemd/system/kube-controller-manager.service || { log_error "failed to remove service file"; sc=1; } }
+    __rm_if_exist /etc/systemd/system/kube-apiserver.service || sc=1
+    __rm_if_exist /etc/systemd/system/kube-controller-manager.service || sc=1
+    __rm_if_exist /etc/systemd/system/kube-scheduler.service || sc=1
     
     return $sc
 }
@@ -75,7 +88,7 @@ _create_directories() {
     log_debug "created directories for services"
 }
 
-
+# again, using set -e is not a good practice, but we're doing it with caution
 _install_configurations() {
     _create_directories || return 1
     # run a subshell so that we can use -e without exiting the script
@@ -100,14 +113,12 @@ _install_configurations() {
     )
 }
 
-_install_service_files() {(
-    set -e
-    trap _delete_service_files ERR
-    cp ${cp_home}/kube-apiserver.service /etc/systemd/system
-    cp ${cp_home}/kube-controller-manager.service /etc/systemd/system
-    cp ${cp_home}/kube-scheduler.service /etc/systemd/system
+_install_service_files() {
+    cp ${cp_home}/kube-apiserver.service /etc/systemd/system || return 1
+    cp ${cp_home}/kube-controller-manager.service /etc/systemd/system || return 1
+    cp ${cp_home}/kube-scheduler.service /etc/systemd/system || return 1
     
-)}
+}
 
 _enable_services() {
     systemctl daemon-reload || { log_error "failed to daemon-reload"; return 1; }
@@ -135,7 +146,7 @@ _enable_services() {
 #   including kube-apiserver, kube-controller-manager,
 #   and kube-scheduler
 #
-################
+#
 
 install_binaries() {
     if [ "$(_check_binaries_installed)" = "true" ]; then
@@ -163,12 +174,6 @@ install_binaries() {
     log_info "installed control plane binaries"
 }
 
-################
-#
-#   uninstall the control plane binaries
-#
-#################
-
 uninstall_binaries() {
     if [ "$(_check_services_loaded)" = "true" ]; then
         log_warning "services are loaded, unload them first"
@@ -190,7 +195,7 @@ uninstall_binaries() {
 #   the control plane services, i.e. creating
 #   directories, copying certifiates, etc.
 #
-###################
+#
 
 install_services() {
     if [ "$(_check_services_loaded)" = "true" ]; then
@@ -204,19 +209,14 @@ install_services() {
     
     echo_title "installing services"
 
-    _install_configurations || {  log_error "failed installing certificates and kubeonfigs"; return 1; } 
+    _install_configurations 
+    if [ $? != 0 ]; then  log_error "failed installing certificates and kubeonfigs"; return 1; fi 
     _install_service_files || { _delete_configurations; log_error "failed intsalling service files"; return 1; }
     _enable_services || { _delete_configurations; _delete_service_files; log_error "failed to enable services"; return 1; }
 
     log_info "installed services"
 
 }
-
-####################
-#
-#   undo the install_services function
-#
-####################
 
 uninstall_services() {
     if [ "$(_check_services_loaded)" = "false" ]; then
@@ -240,12 +240,8 @@ uninstall_services() {
 }
 
 
-#######################
-#
-#   start the control plane services
-#
-#########################
 
+# start the control plane services
 start_services() {
     if [ $(_check_services_active) = "true" ]; then
         log_warning "service already running"
@@ -260,18 +256,11 @@ start_services() {
         return 3
     fi
 
-
     # if one fails to start, the others are started, but the exit code is non-zero
     systemctl start kube-apiserver kube-scheduler kube-controller-manager || { log_error "failed to start services"; return 1;  }
 
     log_info "started control plane services"
 }
-
-#################
-#   
-#   stop the contorl plane services
-#
-###################
 
 stop_services() {
     # if one fails to stop, the others are stopped, but exit code is non-zero
@@ -287,16 +276,14 @@ stop_services() {
 
 
 
-############### status functions
-
+############### status functions ##############
 
 status() {
-    json='{"installed": true, "loaded": true}'
     local is_installed=$(_check_binaries_installed)
     local is_loaded=$(_check_services_loaded)
     local is_landed=$(_check_landed)
     local is_active=$(_check_services_active)
-    echo $json | jq ".installed |= $is_installed | .loaded |= $is_loaded | .active |= $is_active | .landed |= $is_landed"
+    echo '{}' | jq ".installed |= $is_installed | .loaded |= $is_loaded | .active |= $is_active | .landed |= $is_landed"
 }
 
 
@@ -318,12 +305,9 @@ _check_services_active() {
 #
 #   check service loaded
 #   
-#   true if: 
-#       - directories exist (making an assumption that the files are there)
-#       - all services enabled: kube-apiserver, kube-scheduler, kube-controller-manager
+#   true if all services enabled: kube-apiserver, kube-scheduler, kube-controller-manager
 
 _check_services_loaded() {
-    test -d /etc/kubernetes && test -d /var/lib/kubernetes && \
        systemctl is-enabled kube-apiserver > /dev/null 2>&1 && \
        systemctl is-enabled kube-scheduler > /dev/null 2>&1  && \
        systemctl is-enabled kube-controller-manager > /dev/null 2>&1 && echo "true" || echo "false"
diff --git a/kthw/etcd/etcd_agent.sh.template b/kthw/etcd/etcd_agent.sh.template
--- a/kthw/etcd/etcd_agent.sh.template
+++ b/kthw/etcd/etcd_agent.sh.template
@@ -2,8 +2,8 @@
 
 cmd=$1
 
-etcd_home={{etcd_home}}
-etcd_version={{etcd_version}}
+etcd_home={{ETCD_HOME}}
+etcd_version={{ETCD_VERSION}}
 
 
 ## Logging functions
@@ -49,16 +49,60 @@ log_success() {
     echo -e "${GREEN}=== $2 $RESET"
 }
 
-####### API functions
+############# Utility functions 
+
+
+__rmdir_if_exist() {
+    [ -z "$1" ] && { log_error "directory not provided"; return 1; }
+    [ -d $1 ] && { rm -rf $1  || { log_error "failed to remove directory $1"; return 1; } }
+    return 0
+}
+
+__rm_if_exist() {
+    [ -z "$1" ] && { log_error "file not provided"; return 1; }
+    [ -f $1 ] && { rm -rf $1 || { log_error "failed to remove file $1"; return 1; } }
+    return 0
+}
+
+
+_create_directories() {
+    mkdir -p /etc/etcd /var/lib/etcd || { log_error "failed to create directories"; return 1; }
+    log_debug "directories created"
+}
+
+_delete_directories() {
+    __rmdir_if_exist "/etc/etcd"
+    __rmdir_if_exist "/var/lib/etcd"
+    
+    log_debug "directories removed"
+}
+
+_copy_certificates() {
+    cp $etcd_home/ca-etcd.crt /etc/etcd || { log_error "failed to copy certificates"; return 1; }
+    cp $etcd_home/etcd-server.crt /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
+    cp $etcd_home/etcd-server.key /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
+}
+
+_copy_unit_file() {
+    cp $etcd_home/etcd.service /etc/systemd/system  || { log_error "failed to copy service file"; return 1; }
+}
+
+_delete_unit_file() {
+    __rm_if_exist /etc/systemd/system/etcd.service 
+}
+
+_test_installation() {
+    if etcd --version; then return 0; else return 1; fi
+}
+
+
+######### commands functions ##################
 
 ##### 
 #   installing the etcd software
 #   
-#   Returns 0 on success, 1 on error
 #   on success, installs etcd binaries in /usr/local/bin
-#   idempotent - will only run if not already installed
 #
-#####
 install_etcd_binaries() {
     if [ $(_check_binaries_installed) = "true" ]; then
         log_warning "binaries already installed !"
@@ -93,7 +137,6 @@ install_etcd_binaries() {
 #   on success, uninstalls etcd binaries from /usr/local/bin
 #   runs only if: etcd installed and service unloaded
 #
-#####
 
 uninstall_etcd_binaries() {
     if [ $(_check_binaries_installed) = "false" ]; then
@@ -120,9 +163,8 @@ uninstall_etcd_binaries() {
 #   - copy service file to correct location
 #   - load and enable the service
 #
-#   runs only if in 'landed' state, and service not already loaded
+#   runs only if in 'installed' state, and service not already loaded
 #
-##############
 
 install_service() {
     if [ $(_check_service_loaded) = "true" ]; then
@@ -165,8 +207,6 @@ install_service() {
 #
 #   runs only if service is not active and is loaded
 #
-###################
-
 uninstall_service() {
     if [ $(_check_service_active) = "true" ]; then
         log_warning "service is active, stop service first"
@@ -194,7 +234,7 @@ uninstall_service() {
 #   
 #   runs only if service is loaded
 #
-###############
+
 start_service() {
     if [ $(_check_service_active) = "true" ]; then
         log_warning "service already running"
@@ -226,7 +266,7 @@ start_service() {
 #
 #   runs only if service is active
 #
-##################
+
 stop_service() {
     if [ $(_check_service_active) = "false" ]; then
         log_warning "service already stopped"
@@ -240,56 +280,14 @@ stop_service() {
 
 }
 
-## Utility functions
-_create_directories() {
-    mkdir -p /etc/etcd /var/lib/etcd || { log_error "failed to create directories"; return 1; }
-    log_debug "directories created"
-}
+########## status functions #################
 
-_delete_directories() {
-    if [ ! -d /etc/etcd ]; then
-        log_warning "/etc/etcd doesn't exist"
-    fi
-    if [ ! -d /var/lib/etcd ]; then
-        log_warning "/var/lib/etcd doesn't exist"
-    fi
-    rm -rf /var/lib/etcd /etc/etcd || log_error "failed to remove /var/lib/etcd"
-    log_debug "directories removed"
-    
-}
-
-_copy_certificates() {
-    cp $etcd_home/ca-etcd.crt /etc/etcd || { log_error "failed to copy certificates"; return 1; }
-    cp $etcd_home/etcd-server.crt /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
-    cp $etcd_home/etcd-server.key /etc/etcd || { log_error "failed to copy certificates"; rm /etc/etcd/*; return 1; }
-}
-
-_copy_unit_file() {
-    cp $etcd_home/etcd.service /etc/systemd/system  || { log_error "failed to copy service file"; return 1; }
-}
-
-_delete_unit_file() {
-    if [ -f /etc/systemd/system/etcd.service ]; then
-        rm /etc/systemd/system/etcd.service || { log_error "failed to remove unit file"; return 1; }
-    else
-        warn "unit file doesn't exist"
-    fi
-}
-
-_test_installation() {
-    if etcd --version; then return 0; else return 1; fi
-}
-
-
-########## check status functions of etcd
 _check_service_loaded() {
-    test -d /etc/etcd && test -d /var/lib/etcd && \
-    systemctl list-units --all | grep etcd 2>&1 > /dev/null && \
-    systemctl is-enabled etcd 2>&1 > /dev/null && echo "true" || echo "false"
+    systemctl is-enabled etcd > /dev/null 2>&1  && echo "true" || echo "false"
 }
 
 _check_service_active() {
-    systemctl is-active etcd 2>&1 > /dev/null && echo "true" || echo "false"
+    systemctl is-active etcd > /dev/null 2>&1 && echo "true" || echo "false"
 }
 
 _check_binaries_installed() {
@@ -303,12 +301,11 @@ _check_landed() {
 }
 
 status() {
-    json='{"installed": true, "loaded": true}'
     local is_installed=$(_check_binaries_installed)
     local is_loaded=$(_check_service_loaded)
     local is_landed=$(_check_landed)
     local is_active=$(_check_service_active)
-    echo $json | jq ".installed |= $is_installed | .loaded |= $is_loaded | .active |= $is_active | .landed |= $is_landed"
+    echo '{}' | jq ".installed |= $is_installed | .loaded |= $is_loaded | .active |= $is_active | .landed |= $is_landed"
 }
 
 
